apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBiliYcrN8Zkov1rnm7ufbYVGUPuit9ozY6FxSGdFrB974jggkw25EaKkcMRNU5CgOXCnxF8H8SONpYJcFaWDTZB2EQhbA0owbmhVDEUuiT+myftDqdVAtQEbmaXj6F7544hdH9fajXTs6dSoC1vk1snMpaX6fYp3J9/qEqsQgveB6A8v/zJEiVz/hMtqb0EkRMEXSByTadbXyzPzIipJYxm+4Rb/7S9pykAz9IzFC0c7stUj3Zff3CDBsRUq9nPKE9ADvAV7EP7NRa+n6+eErV1fpB05GBJ+luImExm6bf/w+76ZuszS0T4IHY4ap/HI6WTGl2KA0ZsZyXzEn3QRIcbrrB8u2EuXeOLHsz/Q8bW3m4TjHVTLnS3oztJIy540p4jCIUJbgFCsrCit9JEB3L+NHrhsZ5CdgUrmiVhDuiZelqOOZPjVmVkYH52GezVXsh1yRjTVtIS8l3gSqx5sEMIK+d1m/nEUdPcxPYk06fwESW8lkq+A+bpk2L4d2cnMseI868Xk9n9blB2Kk4OdF/582jYP+7XDM7VzHFw5XYLrBATj+3yzswZ+jMDtsnccpi4NwXilrUsCwORZMixpM7BJbEe469Djs7pHKwyenWYIMHdJzCI46bHQSAVSVrvC2zhEpOQnKc92zUcG0sj/eZ0l3e12/I+ZKxF4dTfLRKe7d4s+bJ/5XQpRDKr/2kOemymn5CZN1+9VUcVe9cBAQcNsnq+Q==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
