apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCuFkAsgLzfeCWKaE0m43eaK6/mXfJvnIYP2izqc11vFK0ERiz9TUr1SfFrJlQDeoxeyz2V9r3Dw/WMDSUfG6ozjXopXx3oOOyL/LNsBAM0fDS/TyfltG6RGZ78LpTgnOfWFWB+x96ESqNd5/WEFlyIqDAp9Shc08tChIr+It+KdJy8C5QPhZU2U76ptSrwmNO0BKq1/sRP6JTZEGkqGx8wvtaw8oe6Lhq1np+KOmLD0apRlZboK0v23R3AH/Ds+dDI456A1WLh9z3AAdHkWcadBwsdZI84n00C7u7gkcqgQYdXgtn/beK2BX+OTRZffRWdSwqWh9Ipb/lv4eBrqCGcT06oGjf5N7hTKPq9RvExFIf7DGQ4PfzuezRJK54K/hOtcS12KuvnK5bQGP94UF24Lb2+EzXZnZyu2Uim1QcqINGFOd4UbDmCx5NCUaVJm/UCRoOsIleUS/dFojcGZkYslzihlzWM3lAMVU/AUsK3Tbll5gE5jpy9Xwore334ccdLKb59N7GRsSKdOynEm/InxpUn6MKQlae/WHz9G6w2iwfKvAHTTD3BCtdNRWfYOw/APgHQEs1Sg0T2yXtpo+pnuHniottMaVXSEdTsoyBVjTMOUQtCDe1EPYUbmjmvjBgrzZAHGaaQHobv1H4eD6ZCIWdizlTxR9w9TcaBAF05kzP6XDluypHqInr/y3TG0CLHDNNDlMd1HzvzBMbNLbhu64AEJA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
